/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppAbout {
    }
    interface AppExperience {
    }
    interface AppNav {
    }
    interface AppRoot {
    }
    interface AppWork {
    }
    interface DsCard {
        "full": boolean;
        "head": string;
        "subhead"?: string;
    }
    interface DsPopover {
        "popId": string;
    }
}
declare global {
    interface HTMLAppAboutElement extends Components.AppAbout, HTMLStencilElement {
    }
    var HTMLAppAboutElement: {
        prototype: HTMLAppAboutElement;
        new (): HTMLAppAboutElement;
    };
    interface HTMLAppExperienceElement extends Components.AppExperience, HTMLStencilElement {
    }
    var HTMLAppExperienceElement: {
        prototype: HTMLAppExperienceElement;
        new (): HTMLAppExperienceElement;
    };
    interface HTMLAppNavElement extends Components.AppNav, HTMLStencilElement {
    }
    var HTMLAppNavElement: {
        prototype: HTMLAppNavElement;
        new (): HTMLAppNavElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppWorkElement extends Components.AppWork, HTMLStencilElement {
    }
    var HTMLAppWorkElement: {
        prototype: HTMLAppWorkElement;
        new (): HTMLAppWorkElement;
    };
    interface HTMLDsCardElement extends Components.DsCard, HTMLStencilElement {
    }
    var HTMLDsCardElement: {
        prototype: HTMLDsCardElement;
        new (): HTMLDsCardElement;
    };
    interface HTMLDsPopoverElement extends Components.DsPopover, HTMLStencilElement {
    }
    var HTMLDsPopoverElement: {
        prototype: HTMLDsPopoverElement;
        new (): HTMLDsPopoverElement;
    };
    interface HTMLElementTagNameMap {
        "app-about": HTMLAppAboutElement;
        "app-experience": HTMLAppExperienceElement;
        "app-nav": HTMLAppNavElement;
        "app-root": HTMLAppRootElement;
        "app-work": HTMLAppWorkElement;
        "ds-card": HTMLDsCardElement;
        "ds-popover": HTMLDsPopoverElement;
    }
}
declare namespace LocalJSX {
    interface AppAbout {
    }
    interface AppExperience {
    }
    interface AppNav {
    }
    interface AppRoot {
    }
    interface AppWork {
    }
    interface DsCard {
        "full"?: boolean;
        "head"?: string;
        "subhead"?: string;
    }
    interface DsPopover {
        "popId"?: string;
    }
    interface IntrinsicElements {
        "app-about": AppAbout;
        "app-experience": AppExperience;
        "app-nav": AppNav;
        "app-root": AppRoot;
        "app-work": AppWork;
        "ds-card": DsCard;
        "ds-popover": DsPopover;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-about": LocalJSX.AppAbout & JSXBase.HTMLAttributes<HTMLAppAboutElement>;
            "app-experience": LocalJSX.AppExperience & JSXBase.HTMLAttributes<HTMLAppExperienceElement>;
            "app-nav": LocalJSX.AppNav & JSXBase.HTMLAttributes<HTMLAppNavElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-work": LocalJSX.AppWork & JSXBase.HTMLAttributes<HTMLAppWorkElement>;
            "ds-card": LocalJSX.DsCard & JSXBase.HTMLAttributes<HTMLDsCardElement>;
            "ds-popover": LocalJSX.DsPopover & JSXBase.HTMLAttributes<HTMLDsPopoverElement>;
        }
    }
}
